name: Check





on: push





jobs:

  checking:
    name: Check
    runs-on: ubuntu-18.04

    steps:

      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install && npm install jest-sonar-reporter
      - run: npm run test -- --verbose --testResultsProcessor=jest-sonar-reporter

      - name: report path correction
        run: |-
          sed -i 's#SF:/.*/lib/#SF:/github/workspace/lib/#g' coverage/lcov.info
          sed -i 's#/home/runner/.*/test/#/github/workspace/test/#g' test-report.xml

      - run: npm run build

      - run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - uses: sonarsource/sonarcloud-github-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

