name: Check





on: push





jobs:

  checking:
    name: Check
    runs-on: ubuntu-18.04

    steps:

      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          version: 12.x

      - run: npm install
      - run: npm run test
      - run: npm run build

      - run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

